# (Tokyo Night) color scheme for Emilia Rice

# Default colors
[colors.primary]
background = "#282828"
foreground = "#eddbb2"

# Cursor colors
[colors.cursor]
cursor = "#458588"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#83a598"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

# Bright colors
[colors.bright]
black = "#1d2021"
blue = "#076678"
cyan = "#458588"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#f9f5d7"
yellow = "#d79921"
