#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         0
bspc config window_gap          7
bspc config border_color        #eba0ac

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart Applications 
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
flameshot &
$ xsetroot -Colloid-Pastel-Light-Cursors left_ptr &

